### PR TITLE
fix(colors): apply terminal highlights more consistently

### LINKED ISSUE #230: Plugin isn't setting or using NormalFloat highlight
I've been trying for some time to get the background color of the floating terminals to match the colors of the split ones, without success. I tried to investigate in the code and it seems to me that the plugin isn't setting the floating window to use the NormalFloat highlight, but I don't know Lua enough to be 100% sure of that.

I'd send some pics, but the images in the readme already illustrate the problem.

I tried manually setting the color in the setup() function, but it also doesn't work. These colors can't bee seen anywhere.

q_003

### PR DESCRIPTION
**Pull request by akinsho**
Also fix the issue of user highlights never being actually taken into account, and update the users highlights when the colorscheme changes.

fixes #230 #223 

@paulo-santana @Liverm0r can you both please test this PR

### CODE REVIEW

**Comment by paulo-santana** [comment]
Now setting the highlights in the setup works fine. The 'link' config still doesn't.
q_005

**Comment by Liverm0r** [comment]
works, thanks!

**Comment by akinsho** [comment]
@paulo-santana can you try the link key again, I wasn't passing this on before

**Comment by paulo-santana** [comment]
@akinsho Now every ToggleTerm highlights have stopped working xD

q_007

**Comment by akinsho** [comment]
@paulo-santana that's very strange and doesn't sound right, can you confirm how you are setting highlights since they shouldn't all break just because links were specified. Unless you are doing some linking of your own

**Comment by paulo-santana** [comment]
This is how I'm setting them up
q_008

Does this happen only with me?

**Comment by paulo-santana** [comment]
As a clarification, I tried disabling all other plugins that could mess with the highlights, the issue continues.

I discovered the plugin doesn't set the highlights until the first terminal is open. After that, the highlights appear on the listing, but the `ToggleTerm1NormalFloat` and `ToggleTerm1FloatBorder` are linking back to global Normal.
q_009


I tried setting the plugin's normal to red, and the split terminal does get the color. However, the floating ones don't.
q_010

**Comment by akinsho** [comment]
@paulo-santana this should now be fixed this has all gotten quite complex, so I'll likely reject almost all future PRs related to highlighting. Trying to accommodate user feature requests has led to way too much complexity. Hopefully it resolves both your issues and I can call it a day.

**Comment by paulo-santana** [comment]
@akinsho yup, it works fine now. Thank you for your work!

**Pull request merged**
