### PR TITLE
feat(toggleterm): add a simple winbar to show terminal data

### PR DESCRIPTION
**Pull request by akinsho**
This is currently blocked by a weird bug where the `winhighlight` for the `WinBar` does not get applied correctly. Possibly due to https://github.com/neovim/neovim/issues/18628

### CODE REVIEW

**Comment by famiu** [comment]
The bug is fixed now in the latest Neovim master

**Comment by akinsho** [comment]
@famiu FYI I discovered that the issue I'm seeing is due to a different problem, I just realised that you can't set the `winhighlight` of the `Winbar` e.g. `setlocal winhighlight=Winbar:Number` won't work i.e. it will error saying it is invalid however `setlocal winhighlight=Normal:Number` does work.

**Comment by famiu** [comment]
> @famiu FYI I discovered that the issue I'm seeing is due to a different problem, I just realised that you can't set the `winhighlight` of the `Winbar` e.g. `setlocal winhighlight=Winbar:Number` won't work i.e. it will error saying it is invalid however `setlocal winhighlight=Normal:Number` does work.

Ah, I don't think I can help you with that. `winhighlight` currently is problematic with a lot of things. Hopefully it'll be fixed soon.

**Comment by akinsho** [comment]
image

**Pull request merged**
