### PR TITLE
feat(config): allow `shell` parameter to be a function

### PR DESCRIPTION
**Pull request by jakubkaczor**
This enables determining the default shell dynamically. Please let me know if you are ok with such a change. If so, I will update the documentation.

### CODE REVIEW

**Comment by akinsho** [comment]
@jakubkaczor thanks for the PR. Personally I don't mind at all. If you could make this query stylistically the same as other similar options that'd be great, I'm not sure the other similar options call the function inline like that. Maybe they do, on mobile so haven't checked

**Comment by jakubkaczor** [comment]
@akinsho, what do you mean by “stylistically the same”? In terms of documentation?

Also, what does it mean for an option to call a function? The only function field in the configuration I located is `winbar.name_formatter`, which is directly called. Are you talking about the type checking of the configuration field? With this change, `shell` is the only field that is of a type that is a union of other types, so I don't think similarity in the field value use could be achieved.

**Comment by jakubkaczor** [comment]
Excuse me. The `size` field can also be a function, but in the code, in the comment around declaration of the field it is documented as a number, hence my mistake. Do you mean to use something similar as `ui._resolve_size` function? If so, is it needed?

**Comment by akinsho** [comment]
@jakubkaczor never mind about my comment I didn't mean to cause confusion. I thought maybe this plugin declared functions in a different way I'll have a look at this again

**Comment by akinsho** [comment]
@jakubkaczor never mind about my comment I didn't mean to cause confusion. I thought maybe this plugin declared functions in a different way I'll have a look at this again

**Review by akinsho — APPROVED** [review]
LGTM

**Comment by akinsho** [comment]
@jakubkaczor can you add documentation about this feature in the help docs and README.

Would also be nice to have a small test case that essentially launches a terminal with a function `cmd` and checking that it produces the correct command.

**Comment by jakubkaczor** [comment]
> @jakubkaczor can you add documentation about this feature in the help docs and README.
> 
> Would also be nice to have a small test case that essentially launches a terminal with a function `cmd` and checking that it produces the correct command.

Yes. You asked if I could add documentation to the help docs. Isn't it auto-generated by panvimdoc? Therefore, I left that out. If I shouldn't have, please clarify. 😉 And please, let me know if the test is in the form you expected.

**Comment by akinsho** [comment]
@jakubkaczor changes look good thanks for making them, and the test case is fine, just wanted something in place to safeguard this feature against future changes in case myself or someone else accidentally forgets that command can be a function and it gets removed at some point

**Comment by jakubkaczor** [comment]
I understand. Thanks for explanation. 😉

**Pull request merged**
